<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1.1 (Python 3.13.0 on win32)" generated="2024-11-21T17:07:37.704229" rpa="false" schemaversion="5">
<suite id="s1" name="Main" source="D:\testtt\main.robot">
<test id="s1-t1" name="Case1createaccount" line="8">
<kw name="createaccount" owner="createaccount">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-11-21T17:07:38.030028" level="INFO">Opening browser 'chrome' to base url 'https:google.com'.</msg>
<arg>https:google.com</arg>
<arg>chrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2024-11-21T17:07:38.029833" elapsed="7.155953"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" start="2024-11-21T17:07:45.188437" elapsed="2.509790"/>
</kw>
<status status="PASS" start="2024-11-21T17:07:38.029009" elapsed="9.669531"/>
</kw>
<tag>Regression</tag>
<tag>TESTDbug</tag>
<status status="PASS" start="2024-11-21T17:07:38.027825" elapsed="9.671310"/>
</test>
<status status="PASS" start="2024-11-21T17:07:37.706488" elapsed="9.995608"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="1" fail="0" skip="0">Regression</stat>
<stat pass="1" fail="0" skip="0">TESTDbug</stat>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Main">Main</stat>
</suite>
</statistics>
<errors>
<msg time="2024-11-21T17:07:38.025750" level="ERROR">Error in file 'D:\testtt\main.robot' on line 3: Resource file 'TestCase\Phonix\Setting\ValidationOnSettingEditOrganization.txt' does not exist.</msg>
</errors>
</robot>
